### ISSUE TITLE
issue with your code

### ISSUE THREAD

**Issue by TuniDev83** [0x77ff/How-to-build-a-WIFI-jammer#1]
.arduinoIDE-unsaved2024528-15548-1toexnw.xn38\sketch_jun28a\sketch_jun28a.ino:10:21: note: suggested alternative: 'RF24_2MBPS'
   radio.setDataRate(RF24_MPS);
                     ^~~~~~~~
                     RF24_2MBPS

exit status 1

Compilation error: 'RF24_MPS' was not declared in this scope

**Comment by 0x77ff** [comment]
replace RF24_MPS with RF24_2MBPS and it should work
